CREATE DATABASE movie_rater;
\c movie_rater;

CREATE USER master_user WITH PASSWORD '1234';
GRANT ALL PRIVILEGES ON DATABASE movie_rater to master_user;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE E_MEDIA_STORAGE_TYPE AS ENUM (
    'S3',
    'FILE_SERVER',
    'LOCAL'
);

CREATE TYPE E_IMAGE_TYPE AS ENUM (
    'PROFILE',
    'MOVIE',
    'PARTICIPANT'
);

CREATE TABLE "IMG_IMAGE"(
    "IMG_ID" uuid PRIMARY KEY  DEFAULT uuid_generate_v4 () NOT NULL,
    "IMG_PATH" VARCHAR(300) NOT NULL,
    "IMG_STORAGE_TYPE" E_MEDIA_STORAGE_TYPE NOT NULL DEFAULT 'LOCAL',
    "IMG_IMAGE_TYPE" E_IMAGE_TYPE NOT NULL,
    UNIQUE("IMG_PATH", "IMG_STORAGE_TYPE")
);

CREATE TYPE E_ROLE AS ENUM (
    'ADMIN',
    'USER',
    'APPLICATION'
);

CREATE TABLE "USU_USER"(
    "USU_ID" uuid PRIMARY KEY  DEFAULT uuid_generate_v4 () NOT NULL,
    "USU_NAME" VARCHAR(40) NOT NULL,
    "USU_PASSWORD" VARCHAR(200) NOT NULL,
    "USU_EMAIL" VARCHAR(100) UNIQUE NOT NULL,
    "USU_DESCRIPTION" VARCHAR(300),
    "USU_BIRTHDAY" DATE NOT NULL,
    "USU_ACTIVE_STATUS" BOOLEAN NOT NULL DEFAULT TRUE,
    "USU_PROFILE_IMAGE" uuid,
    CONSTRAINT "FK_PROFILE_IMAGE"
        FOREIGN KEY ("USU_PROFILE_IMAGE")
        REFERENCES "IMG_IMAGE"("IMG_ID")
);

CREATE TABLE "ROU_ROLE_USER"(
    "ROU_USU_ID" uuid not null,
    "ROU_ROLE" E_ROLE not null DEFAULT 'USER',
    CONSTRAINT "FK_USU_ID"
        FOREIGN KEY ("ROU_USU_ID")
        REFERENCES "USU_USER"("USU_ID"),
    PRIMARY KEY("ROU_USU_ID","ROU_ROLE")
);

CREATE TABLE "PAR_PARTICIPANT"(
    "PAR_ID" uuid PRIMARY KEY  DEFAULT uuid_generate_v4 () NOT NULL,
    "PAR_NAME" VARCHAR(100) UNIQUE NOT NULL,
    "PAR_ORIGIN_COUNTRY" VARCHAR(100) NOT NULL,
    "PAR_DESCRIPTION" VARCHAR(100),
    "PAR_IMAGE" uuid,
    CONSTRAINT "FK_IMAGE"
        FOREIGN KEY ("PAR_IMAGE")
        REFERENCES "IMG_IMAGE"("IMG_ID")

);

CREATE TABLE "MOV_MOVIE"(
    "MOV_ID" uuid PRIMARY KEY  DEFAULT uuid_generate_v4 () NOT NULL,
    "MOV_NAME" VARCHAR(50) NOT NULL,
    "MOV_YEAR" SMALLINT NOT NULL,
    "MOV_DIRECTOR" uuid NOT NULL,
    "MOV_STUDIO" VARCHAR(50) NOT NULL,
    "MOV_POSTER" uuid,
    CONSTRAINT "FK_DIRECTOR"
        FOREIGN KEY ("MOV_DIRECTOR")
        REFERENCES "PAR_PARTICIPANT"("PAR_ID"),

    CONSTRAINT "FK_POSTER"
        FOREIGN KEY ("MOV_POSTER")
        REFERENCES "IMG_IMAGE"("IMG_ID")
);

CREATE TABLE "CAS_CAST"(
    "CAS_MOV_ID" uuid NOT NULL,
    "CAS_PAR_PARTICIPANT" uuid NOT NULL,
    "CAS_CHARACTER" VARCHAR(100) NOT NULL,
    PRIMARY KEY("CAS_MOV_ID", "CAS_PAR_PARTICIPANT", "CAS_CHARACTER"),

    CONSTRAINT "FK_MOVIE"
        FOREIGN KEY ("CAS_MOV_ID")
        REFERENCES "MOV_MOVIE"("MOV_ID"),

    CONSTRAINT "FK_PARTICIPANT"
        FOREIGN KEY ("CAS_PAR_PARTICIPANT")
        REFERENCES "PAR_PARTICIPANT"("PAR_ID")

);


CREATE TABLE "REV_REVIEW"(
    "REV_ID" uuid PRIMARY KEY  DEFAULT uuid_generate_v4 () NOT NULL,
    "REV_TITLE" VARCHAR(30) NOT NULL,
    "REV_STARS" SMALLINT NOT NULL,
    "REV_TEXT" VARCHAR(4000),
    "REV_LIKES" SMALLINT NOT NULL DEFAULT 0,
    "REV_UNLIKES" SMALLINT NOT NULL DEFAULT 0,
    "REV_USU_ID" uuid NOT NULL,
    "REV_MOV_ID" uuid NOT NULL,

    CONSTRAINT "FK_USER"
        FOREIGN KEY ("REV_USU_ID")
        REFERENCES "USU_USER"("USU_ID"),

    CONSTRAINT "FK_MOVIE"
        FOREIGN KEY ("REV_MOV_ID")
        REFERENCES "MOV_MOVIE"("MOV_ID"),

    CONSTRAINT "VALID_REV_STARS_VALUE"
        CHECK("REV_STARS"<=5),

    UNIQUE("REV_USU_ID", "REV_MOV_ID")
);
